# Generated by Django 3.2.2 on 2021-06-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0004_auto_20210603_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighbourhood',
            options={'ordering': ['-date']},
        ),
    ]
