# Generated by Django 3.2.2 on 2021-06-04 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0010_auto_20210604_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood_post', to='neighborhood.neighbourhood'),
        ),
    ]
